FROM fluent/fluentd:v1.16-debian-1

USER root

RUN gem uninstall elasticsearch elasticsearch-api elasticsearch-transport -a -x || true

RUN gem install elasticsearch -v 8.13.0

RUN gem install fluent-plugin-elasticsearch

USER fluent