apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-app-properties-config
data:
  application.properties: |
{{- if eq .Values.env "dev" }}
{{ (.Files.Get "config/dev/appproperties.conf") | nindent 4 }}
{{- else if eq .Values.env "uat" }}
{{ (.Files.Get "config/uat/appproperties.conf") | nindent 4 }}
{{- else if eq .Values.env "prod" }}
{{ (.Files.Get "config/prod/appproperties.conf") | nindent 4 }}
{{- else if eq .Values.env "proddrc" }}
{{ (.Files.Get "config/proddrc/appproperties.conf") | nindent 4 }}
{{- else }}
{{ (.Files.Get "config/dev/appproperties.conf") | nindent 4 }}
{{- end }}