apiVersion: v1
kind: Service
metadata:
  name: {{ include "mufapplication.fullname" . }}
  labels:
    {{- include "mufapplication.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.targetPort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "mufapplication.selectorLabels" . | nindent 4 }}