ports:
  http: 9090
api_gateway:
  url: "http://100.87.70.99:25155/rest/apigateway"
  user: ${APIGW_USER}
  password: ${APIGW_PASSWORD}
  download_settings: true
downloads:
  apis: "	Training_Arbi"
microgatewayPool:
  microgatewayPoolName: mcgwfinance
  microgatewayPoolDescription: Microgateways of a	Training
applications_sync:
  enabled: true
  applications_to_sync: "registeredApplications"
  polling_interval_secs: 10
  connection_timeout_secs: 10 
api_endpoint:
  base_path: /
  ignore_api_name: false
logging:
  level: ERROR