apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  config.yml: |
{{- if eq .Values.env "dev" }}
{{- .Files.Get "config/dev/config.yml" | nindent 3 }}
{{- else if eq .Values.env "uat" }}
{{- .Files.Get "config/uat/config.yml" | nindent 3 }}
{{- else if eq .Values.env "prod" }}
{{- .Files.Get "config/prod/config.yml" | nindent 3 }}
{{- else if eq .Values.env "proddrc" }}
{{- .Files.Get "config/proddrc/config.yml" | nindent 3 }}
{{- else }}
{{- .Files.Get "config/dev/config.yml" | nindent 3 }}
{{- end }}
