apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcgwfinance.fullname" . }}
  labels:
    {{- include "mcgwfinance.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.targetPort }}
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
  selector:
    {{- include "mcgwfinance.selectorLabels" . | nindent 4 }}