# Audit Logging details
<system>
  log_level info
</system>
# Transaction Log Source
<source>
    @type tail
    <parse>
     @type json
    </parse>
    tag esbtrxaudit
    path /fluentd/log/trxAudit.log
    pos_file /fluentd/logpos/trxAudit.log.pos
    read_from_head true
</source>
<match esbtrxaudit>
    @type copy
    <store>
     @log_level debug
     <buffer>
        @type memory
        chunk_limit_size 8m
        total_limit_size 512m
        flush_at_shutdown true
        flush_mode interval
        flush_interval 1s
        flush_thread_count 4
        retry_type exponential_backoff
        retry_max_interval 60s
        retry_forever true
        timekey_use_utc false
     </buffer>
     @type elasticsearch
     host elasticsearch
     port 9240
     scheme http
     default_elasticsearch_version 8
     api_version v7
     content_type application/json
     verify_es_version_at_startup false
     suppress_type_name true
     index_name esbtrxaudit-${tag}
     type_name fluentd
     logstash_format true
     logstash_prefix esbtrxaudit-fluentd
     logstash_dateformat %Y-%m-%d
     time_key_format "%Y-%m-%d %H:%M:%S"
     time_key timestamp
     max_retry_get_es_version 6
     flatten_hashes true
     flatten_hashes_separator _
     scheme http
     ssl_verify false
    #  ca_file fluentd/http_ca.crt
    #  user elastic
    #  password elastic
    </store>
</match>
# Server Log Source
<source>
    @type tail
    <parse>
     @type multiline
     format_firstline /\d{4}-\d{2}-\d{2}/
     format1 /^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} WIB) \[(?<messagecode>[^\]]+)\] \(tid=(?<tid>\d+)\) (?<message>.*)/
     time_format %Y-%m-%d %H:%M:%S
     timezone Asia/Jakarta
    </parse>
    tag esbserverlog
    path /fluentd/log/server.log
    pos_file /fluentd/logpos/server.log.pos
    read_from_head true
</source>
<filter esbserverlog>
  @type record_transformer
  <record>
    hostname "#{Socket.gethostname}"
  </record>
</filter>
<match esbserverlog>
    <buffer>
       @type memory
       chunk_limit_size 8m
       total_limit_size 512m
       flush_at_shutdown true
       flush_mode interval
       flush_interval 30s
       flush_thread_count 4
       retry_type exponential_backoff
       retry_max_interval 60s
       retry_forever true
    </buffer>
    @type elasticsearch
    host elasticsearch
    port 9240
    scheme http
    default_elasticsearch_version 8
    api_version v7
    content_type application/json
    verify_es_version_at_startup false
    suppress_type_name true
    # index_name esbserverlog-${tag}
    type_name fluentd
    logstash_format true
    logstash_prefix esbserverlog-fluentd
    logstash_dateformat %Y-%m-%d
    time_key_format "%Y-%m-%d %H:%M:%S"
    time_key timestamp
    max_retry_get_es_version 6
    scheme http
    ssl_verify false
    # ca_file fluentd/http_ca.crt
    # user elastic
    # password elastic
</match>