<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">pokokHutangHelper</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcJb3RySW5wdXQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1
cnNvciwgIm90ciIgKTsNClN0cmluZwlkcElucHV0ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlw
ZWxpbmVDdXJzb3IsICJkcCIgKTsNClN0cmluZwlhc3VyYW5zaUlucHV0ID0gSURhdGFVdGlsLmdl
dFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJhc3VyYW5zaSIgKTsNClN0cmluZwlhZG1pbmlzdHJh
c2lJbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiYWRtaW5pc3Ry
YXNpIiApOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0KDQpkb3VibGUgb3RyID0gcGFyc2VU
b0RvdWJsZShvdHJJbnB1dCk7DQpkb3VibGUgZHAgPSBwYXJzZVRvRG91YmxlKGRwSW5wdXQpOw0K
ZG91YmxlIGFzdXJhbnNpID0gcGFyc2VUb0RvdWJsZShhc3VyYW5zaUlucHV0KTsNCmRvdWJsZSBh
ZG1pbmlzdHJhc2kgPSBwYXJzZVRvRG91YmxlKGFkbWluaXN0cmFzaUlucHV0KTsNCg0KZG91Ymxl
IGNhbGN1bGF0ZVJlc3VsdCA9IG90ciAtIChkcCArIGFzdXJhbnNpICsgYWRtaW5pc3RyYXNpKTsN
Cg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5n
ZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJyZXN1bHQiLCBj
YWxjdWxhdGVSZXN1bHQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOw0KCQ==</value>
</Values>
