<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseDouble</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
Zwlpbml0X2RvdWJsZUlucHV0ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJkb3VibGVJbnB1dCIgKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCg0KZG91YmxlIGRv
dWJsZUlucHV0ID0gcGFyc2VUb0RvdWJsZShpbml0X2RvdWJsZUlucHV0KTsNCg0KU3RyaW5nIHBh
dHRlcm4xID0gIiMjLiMjIyMjIjsNCkxvY2FsZSBsb2NhbGUgPSBuZXcgTG9jYWxlKCJlbiIsICJV
SyIpOw0KDQpEZWNpbWFsRm9ybWF0IGRlY2ltYWxGb3JtYXQgPSAoRGVjaW1hbEZvcm1hdCkgTnVt
YmVyRm9ybWF0LmdldE51bWJlckluc3RhbmNlKGxvY2FsZSk7DQpkZWNpbWFsRm9ybWF0LmFwcGx5
UGF0dGVybihwYXR0ZXJuMSk7DQpEb3VibGUgcmVzdWx0ID0gRG91YmxlLnBhcnNlRG91YmxlKGRl
Y2ltYWxGb3JtYXQuZm9ybWF0KGRvdWJsZUlucHV0KSk7DQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1
cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwu
cHV0KCBwaXBlbGluZUN1cnNvcl8xLCAicGFyc2VSZXN1bHQiLCByZXN1bHQgKTsNCnBpcGVsaW5l
Q3Vyc29yXzEuZGVzdHJveSgpOw0KCQ==</value>
</Values>
